name: ANYad tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Build all
      run: cmake . && make -j4
    - name: Run tests
      run: ctest --verbose

